apiVersion: v1
kind: Service
metadata:
  name: opengrok-bootstrap
  labels:
    run: opengrok-bootstrap
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: opengrok-bootstrap
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: opengrok-bootstrap
spec:
  selector:
    matchLabels:
      run: opengrok-bootstrap
  replicas: 1
  template:
    metadata:
      labels:
        run: opengrok-bootstrap
    spec:
      containers:
      - name: opengrok-bootstrap
        image: omrizcontainerbuilder.azurecr.io/opengrok:v1
        env:
            - name: MONITORED_REPOSITORIES
              value: https://github.com/twbs/bootstrap.git
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth