apiVersion: v1
kind: Service
metadata:
  name: opengrok-multigrok
  labels:
    run: opengrok-multigrok
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: opengrok-multigrok
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: opengrok-multigrok
spec:
  selector:
    matchLabels:
      run: opengrok-multigrok
  replicas: 1
  template:
    metadata:
      labels:
        run: opengrok-multigrok
    spec:
      containers:
      - name: opengrok-multigrok
        image: omrizcontainerbuilder.azurecr.io/opengrok:v1
        env:
            - name: MONITORED_REPOSITORIES
              value: https://github.com/omriz/multigrok.git
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth